.\" Manpage for calc.
.TH man 8 "07 April 2025" "0.2" "calc"
.SH NAME
Calc
.SH SYNOPSIS
calc [expression] [more expressions]
.SH DESCRIPTION
Calc is a simple C terminal dynamic expression calculator.
.SH OPTIONS
Either run "calc [expression] [more expression]"
.TP
Or just "calc" to enter the software
.SH COMMANDS
Mostly normal arithmetic expressions with a few outliers.
.TP
- Exponents "**"
.TP
- "PI" for circles
.SH SEE ALSO
Takes inspiration from qalc
.SH BUGS
Some known bugs are PI being strange and exponents not being able to have other inputs.
.SH AUTHOR
Contact iammethatisyou@gmail.com
