.\" Manpage for calc.
.TH man 8 "07 April 2025" "0.3" "calc"
.SH NAME
Calc
.SH SYNOPSIS
calc [expression] [more expressions]
.SH DESCRIPTION
Calc is a simple C terminal dynamic expression calculator.
.SH OPTIONS
Either run "calc [expression] [more expression]"
.TP
Or just "calc" to enter the software
.TP
Note: When ran in CLI sometimes shells like zsh can mess up characters like '*'
.SH COMMANDS
Mostly normal arithmetic expressions with a few outliers.
.TP
- Exponents "**"
.TP
- "PI" for circles
.SH SEE ALSO
Qalc
.SH Exit stats:
0 	Normal exit status
.TP
1	User input error or small problem
.TP
2	Memory allocation failure or more serious problem
.SH BUGS
Some known bugs are PI being strange and exponents not being able to have other inputs. CLI arguments can also be a problem.
.SH AUTHOR
Contact iammethatisyou@gmail.com
